# Generated by Django 2.2.12 on 2020-04-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentHeader',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='componentheader_componentheader', serialize=False, to='cms.CMSPlugin')),
                ('ComponentHeader_title', models.CharField(default='YOUR FAVORITE SOURCE OF FREE BOOTSTRAP THEMES', max_length=150)),
                ('ComponentHeader_subtitle', models.CharField(default='Start Bootstrap can help you build better websites using the Bootstrap Framework! Just download a theme and start customising, no strings attached!', max_length=150)),
                ('ComponentHeader_button', models.CharField(default='Find out more', max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
